#!/usr/bin/bash

. ~/.env # source file containing STREAM_KEY

FFMPEG=/home/alex/bin/ffmpeg_patched
STREAM_KEY_TEST="$STREAM_KEY?bandwidthtest=true"
STREAM_SERVER=rtmp://sea.contribute.live-video.net
VOD_PATH="$HOME/vods/$(date +%Y-%m-%d_%H%M%S).mkv"

# Webcam using mpv
#webcam_start

echo -n '' >/tmp/ffmpeg.in # This file serves as stdin for ffmpeg. Write 'q' to stop recording.

# Select Sink
SINK="$1"
if [ $# -eq 0 ] ; then
    SINK="vod"
fi

case "$SINK" in
    vod)    echo -n "$VOD_PATH" > ~/stream_key.txt;;
    twitch) echo -n "[f=flv]$STREAM_SERVER/app/$STREAM_KEY" > ~/stream_key.txt;;
    all)    echo -n "$VOD_PATH|[f=flv]$STREAM_SERVER/app/$STREAM_KEY" > ~/stream_key.txt;;
esac

$FFMPEG -y \
    -hide_banner \
    -loglevel error \
    -video_size 1920x1080 \
    -framerate 25 \
    -probesize 42M \
    -f x11grab -i :0.0+0,0 \
    -f pulse -i default \
    -preset ultrafast \
    `#-vf "gblur=10"` \
    -b:v 4500k \
    -b:a 128k \
    -c:v libx264 \
    -c:a aac \
    -map 0 -map 1 \
    -flags +global_header \
    -f tee ~/stream_key.txt </tmp/ffmpeg.in &>/home/alex/vods/log &
pidof $FFMPEG > /tmp/ffmpeg.pid # To display "RECORDING" in i3status

# For quitting
#echo q >/tmp/ffmpeg.in
